import { PrismaClient, type ProductStatus, type SourceType, type Confidence } from '@prisma/client';
import { validateProductAttributeInput } from '../src/lib/products/productAttributeValidator';
import { convertLengthToCanonicalInches } from '../src/lib/products/unitConversion';

// Each product is an independent transaction; category lookup fails before any writes.
const STOCK_IMAGE = 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800&auto=format&fit=crop&q=80';
const source = (asin: string) => `https://www.amazon.com/dp/${asin}`;
type Entry = { key: string; variantId: string | null; valueString?: string; valueNumber?: number; valueBoolean?: boolean };
type ProductDef = { brandSlug: string; brandName: string; name: string; slug: string; upcCode: string | null; description: string; isSustainable: boolean; sku: string; size: string; color: string | null; asin: string; price: number; entries: (variantId: string) => Entry[] };
const PRODUCT_SCOPE_KEYS = new Set(['min_height_in', 'max_height_in', 'max_load_lb', 'product_weight_lb', 'desktop_thickness_in', 'adjustment_type', 'frame_material', 'desktop_shape', 'desktop_included']);
const common = (variantId: string, items: Omit<Entry, 'variantId'>[]) => items.map((item) => ({ ...item, variantId: PRODUCT_SCOPE_KEYS.has(item.key) ? null : variantId }));
const products: ProductDef[] = [
 { brandSlug:'veken',brandName:'Veken',name:'Veken 47.2 Inch Large Electric Standing Desk, Gaming Table (Black)',slug:'veken-47-2in-standing-desk-black',upcCode:'810191341857',description:'Electric standing desk with a 47.24 x 23.64 inch engineered-wood top, steel frame, and 176 lb capacity.',isSustainable:false,sku:'veken-47-2in-standing-desk-black-default',size:'47.2x23.6',color:'Cyber Black',asin:'B0FPX18P4J',price:89.99,entries:(v)=>common(v,[{key:'min_height_in',valueNumber:28.3},{key:'max_height_in',valueNumber:46.5},{key:'max_load_lb',valueNumber:176},{key:'product_weight_lb',valueNumber:42.1},{key:'adjustment_type',valueString:'ELECTRIC'},{key:'frame_material',valueString:'STEEL'},{key:'desktop_shape',valueString:'RECTANGULAR'},{key:'desktop_included',valueBoolean:true},{key:'desktop_width_in',valueNumber:47.24},{key:'desktop_depth_in',valueNumber:23.64},{key:'desktop_material',valueString:'ENGINEERED_WOOD'},{key:'desktop_finish',valueString:'Laminated'},{key:'frame_color',valueString:'Cyber Black'}]) },
 { brandSlug:'claiks',brandName:'Claiks',name:'Claiks Electric Height Adjustable Standing Desk, 48x24 Inch (Rustic Brown)',slug:'claiks-standing-desk-rustic-brown',upcCode:null,description:'Electric height-adjustable standing desk with a 48 x 24 inch engineered-wood top and steel frame.',isSustainable:false,sku:'claiks-standing-desk-rustic-brown-default',size:'48x24',color:'Rustic Brown',asin:'B0BZ7GXM4M',price:109.99,entries:(v)=>common(v,[{key:'min_height_in',valueNumber:28.3},{key:'max_height_in',valueNumber:convertLengthToCanonicalInches(119,'cm')},{key:'max_load_lb',valueNumber:176},{key:'product_weight_lb',valueNumber:41.4},{key:'desktop_thickness_in',valueNumber:.75},{key:'adjustment_type',valueString:'ELECTRIC'},{key:'frame_material',valueString:'STEEL'},{key:'desktop_shape',valueString:'RECTANGULAR'},{key:'desktop_included',valueBoolean:true},{key:'desktop_width_in',valueNumber:47.24},{key:'desktop_depth_in',valueNumber:23.62},{key:'desktop_material',valueString:'ENGINEERED_WOOD'},{key:'frame_color',valueString:'Black'}]) },
 { brandSlug:'fezibo',brandName:'FEZIBO',name:'FEZIBO Standing Desk 48 x 24 Inch Electric Height Adjustable (Maple)',slug:'fezibo-standing-desk-maple',upcCode:null,description:'Electric height-adjustable standing desk with an FSC-certified wood top and steel frame.',isSustainable:true,sku:'fezibo-standing-desk-maple-default',size:'48x24',color:null,asin:'B0F8MHPVPH',price:112.99,entries:(v)=>common(v,[{key:'min_height_in',valueNumber:27.3},{key:'max_height_in',valueNumber:45},{key:'max_load_lb',valueNumber:176},{key:'adjustment_type',valueString:'ELECTRIC'},{key:'frame_material',valueString:'STEEL'},{key:'desktop_shape',valueString:'RECTANGULAR'},{key:'desktop_included',valueBoolean:true},{key:'desktop_width_in',valueNumber:48},{key:'desktop_depth_in',valueNumber:24},{key:'desktop_finish',valueString:'Laminated'}]) },
 { brandSlug:'veken',brandName:'Veken',name:'Veken 55 Inch Large Electric Standing Desk, Gaming Table (Black)',slug:'veken-55in-standing-desk-black',upcCode:'850069632229',description:'Electric standing desk with a 55.12 x 23.64 inch engineered-wood top and steel frame.',isSustainable:false,sku:'veken-55in-standing-desk-black-default',size:'55x23.6',color:'Cyber Black',asin:'B0DWMJCQBX',price:149.98,entries:(v)=>common(v,[{key:'min_height_in',valueNumber:28.3},{key:'max_height_in',valueNumber:46.5},{key:'product_weight_lb',valueNumber:42.1},{key:'adjustment_type',valueString:'ELECTRIC'},{key:'frame_material',valueString:'STEEL'},{key:'desktop_shape',valueString:'RECTANGULAR'},{key:'desktop_included',valueBoolean:true},{key:'desktop_width_in',valueNumber:55.12},{key:'desktop_depth_in',valueNumber:23.64},{key:'desktop_material',valueString:'ENGINEERED_WOOD'},{key:'desktop_finish',valueString:'Laminated'},{key:'frame_color',valueString:'Cyber Black'}]) },
 { brandSlug:'offigo',brandName:'OffiGo',name:'OffiGo 63 Inch Reversible L Shaped Electric Standing Desk (Black)',slug:'offigo-63in-lshape-standing-desk-black',upcCode:null,description:'Reversible L-shaped electric standing desk with a steel frame, engineered-wood top, and backed by a lifetime frame warranty.',isSustainable:false,sku:'offigo-63in-lshape-standing-desk-black-default',size:'63x47.2',color:'Black',asin:'B0FPFSYXNF',price:219.99,entries:(v)=>common(v,[{key:'min_height_in',valueNumber:27.9},{key:'max_height_in',valueNumber:46.1},{key:'max_load_lb',valueNumber:154},{key:'product_weight_lb',valueNumber:61.6},{key:'desktop_thickness_in',valueNumber:.6},{key:'adjustment_type',valueString:'ELECTRIC'},{key:'frame_material',valueString:'STEEL'},{key:'desktop_shape',valueString:'L_SHAPED'},{key:'desktop_included',valueBoolean:true},{key:'desktop_width_in',valueNumber:63},{key:'desktop_depth_in',valueNumber:47.2},{key:'desktop_material',valueString:'ENGINEERED_WOOD'},{key:'desktop_finish',valueString:'Laminated'},{key:'frame_color',valueString:'Black'}]) },
];
export async function createProducts3to7StandingDesks(prisma: PrismaClient) { const category = await prisma.category.findUnique({where:{slug:'standing-desks'}}); if (!category) throw new Error('Required Category "standing-desks" was not found; run the standing-desk attribute seed first.'); const result=[]; for (const p of products) result.push(await prisma.$transaction(async (rawTx) => { const tx = rawTx as PrismaClient; const brand=await tx.brand.upsert({where:{slug:p.brandSlug},update:{name:p.brandName},create:{slug:p.brandSlug,name:p.brandName}}); const product=await tx.product.upsert({where:{slug:p.slug},update:{name:p.name,category:'standing-desks',category_id:category.id,brand_id:brand.id,description:p.description,image_url:STOCK_IMAGE,upc_code:p.upcCode,status:'DRAFT' as ProductStatus,is_indexed:false,is_sustainable:p.isSustainable},create:{name:p.name,slug:p.slug,category:'standing-desks',category_id:category.id,brand_id:brand.id,description:p.description,image_url:STOCK_IMAGE,upc_code:p.upcCode,status:'DRAFT' as ProductStatus,is_indexed:false,is_sustainable:p.isSustainable}}); const found=await tx.productVariant.findFirst({where:{product_id:product.id,sku:p.sku}}); const variant=found ? await tx.productVariant.update({where:{id:found.id},data:{size:p.size,color:p.color,is_active:true}}) : await tx.productVariant.create({data:{product_id:product.id,sku:p.sku,size:p.size,color:p.color,is_active:true}}); const errors=[]; for(const e of p.entries(variant.id)){const d=await tx.attributeDefinition.findUnique({where:{key:e.key}}); if(!d){errors.push(`${e.key}: definition missing`);continue;} const input={productId:product.id,variantId:e.variantId,attributeDefinitionId:d.id,valueString:e.valueString??null,valueNumber:e.valueNumber??null,valueBoolean:e.valueBoolean??null}; const validation=await validateProductAttributeInput(tx,input); if(!validation.valid) errors.push(`${e.key}: ${validation.errors.join('; ')}`); else {const where={product_id:product.id,attribute_definition_id:d.id,variant_id:e.variantId}; const data={...where,value_string:e.valueString??null,value_number:e.valueNumber??null,value_boolean:e.valueBoolean??null,source_url:source(p.asin),source_type:'RETAILER' as SourceType,confidence:'VERIFIED' as Confidence,verified_at:new Date()}; const existing=await tx.productAttribute.findFirst({where}); if(existing) await tx.productAttribute.update({where:{id:existing.id},data}); else await tx.productAttribute.create({data});}} if(errors.length) throw new Error(`${p.slug} attribute validation failed:\n${errors.join('\n')}`); return product;})); return result; }
if(process.argv[1]?.endsWith('create-products-3to7-standing-desks.ts')){const prisma=new PrismaClient();createProducts3to7StandingDesks(prisma).then(r=>console.log(`Products ready: ${r.map(x=>x.slug).join(', ')}`)).catch(e=>{console.error('Create products failed:',e);process.exitCode=1}).finally(()=>prisma.$disconnect())}
